### ISSUE TITLE
Problem saving bags when running on small dataset on science 3

### ISSUE THREAD

**Issue by r0mainK** [src-d/apollo#24]
I ran apollo's bag command with test Siva files I found on science 3. In order for it to work I had to change a couple lines in ml's `batch_transform.py` file and apollo's `bags.py` file. These changes involved the changes in this  [open PR](https://github.com/src-d/apollo/pull/20) as well as a couple more all involving refactoring of the old `model` variable to the new `docfreq_model` that were omitted and commenting out a line containing reference to `quant_model`.

The exact command was: `docker run -it --rm -v /home/romain/io:/io --link bblfshd --link scylla src-d/apollo-rom bags -r /io/siva --batches /io/bags --docfreq /io/bags/docfreq.asdf -f id -f lit -f uast2seq --uast2seq-seq-len 4 -l Java -s 'local[*]' --min-docfreq 5 --bblfsh bblfshd --cassandra scylla --persist MEMORY_ONLY --config spark.executor.memory=4G --config spark.driver.memory=10G --config spark.driver.maxResultSize=4G` 

It seemed to work properly _(log says apollo detected 128 documents, with average bag length of 398.7 and 5395 of vocab size)_ until starting writing docfreq to /io/bags/docfreq.asdf, when I got this error:

`Traceback (most recent call last):`
  `File "/usr/local/bin/apollo", line 11, in <module>`
        `  load_entry_point('apollo', 'console_scripts', 'apollo')()`
  `File "/packages/apollo/apollo/__main__.py", line 258, in main`
       ` return handler(args)`
 ` File "/packages/apollo/apollo/bags.py", line 126, in source2bags`
          `  batcher.docfreq_model.save(args.docfreq)`
 ` File "/usr/local/lib/python3.5/dist-packages/modelforge/model.py", line 270, in save`
           `   write_model(self._meta, tree, output)`
 ` File "/usr/local/lib/python3.5/dist-packages/modelforge/model.py", line 409, in write_model`
             `  asdf.AsdfFile(final_tree).write_to(output, all_array_compression=ARRAY_COMPRESSION)`
 ` File "/usr/local/lib/python3.5/dist-packages/asdf/asdf.py", line 890, in write_to`
              `with generic_io.get_file(fd, mode='w') as fd:`
 ` File "/usr/local/lib/python3.5/dist-packages/asdf/generic_io.py", line 1186, in get_file`
             `   fd = atomicfile.atomic_open(realpath, realmode)`
 ` File "/usr/local/lib/python3.5/dist-packages/asdf/extern/atomicfile.py", line 139, in atomic_open` `delete=False)`
 ` File "/usr/lib/python3.5/tempfile.py", line 688, in NamedTemporaryFile`
       `  (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)`
 ` File "/usr/lib/python3.5/tempfile.py", line 399, in _mkstemp_inner`
 `   fd = _os.open(file, flags, 0o600)`
`FileNotFoundError: [Errno 2] No such file or directory: '/io/bags/.___atomic_writedyrniw3x'`

The problem seems to be linked with modelforge's saving process, from the error log it seems that science 3 hasn't got the latest version of the repo but I couldn't see how that affected it when looking this [diff](https://github.com/src-d/modelforge/pull/20/files#diff-35a2bd687f902882b53d24a0ea359ff1).

**Comment by r0mainK** [comment]
Closing (was due at the time to a problem in `modelforge` if I remember correctly, not happening anymore)
